[general]
live_config_reload = true
import = [ "kanagawa.toml" ]

[window]
opacity = 1

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
size = 14.0
offset = { x = -1, y = -1 }
