[general]
import = [ "kanagawa.toml" ]
live_config_reload = true

[window]
opacity = 0.97
padding = { x = 2, y = 2 }
dynamic_padding = true

[scrolling]
history = 50000

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
bold = { family = "IosevkaTerm Nerd Font", style = "Bold" }
italic = { family = "IosevkaTerm Nerd Font", style = "Italic" }
bold_italic = { family = "IosevkaTerm Nerd Font", style = "Bold Italic" }
offset = { x = -1, y = -1 }
