[general]
import = [ "kanagawa.toml" ]
live_config_reload = true

[window]
opacity = 0.97

[scrolling]
history = 50000

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Light" }
bold = { family = "IosevkaTerm Nerd Font", style = "SemiBold" }
italic = { family = "IosevkaTerm Nerd Font", style = "Light Italic" }
bold_italic = { family = "IosevkaTerm Nerd Font", style = "SemiBold Italic" }
