"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
right_format = """$time"""

[time]
disabled = false
format = '[$time]($style)'
time_format = '%R'
style = 'bright-black'

[nodejs]
format = '\[[node ($version)]($style)\]'
style = "green"

[php]
format = '\[[php ($version)]($style)\]'
style = "purple"

[git_branch]
format = '\[[$branch]($style)\]'
style = "italic bright-yellow"

[git_status]
format = '(\[[$all_status$ahead_behind]($style)\])'
style = 'yellow'
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[python]
format = '\[[py ${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
style = "green"

[directory]
style = "purple"
truncation_length = 2
truncation_symbol = "…/"

[character]
success_symbol = "[❯](bright-green)"
error_symbol = "[❯](bright-red)"

[battery]
disabled = true

[cmd_duration]
disabled = true

[docker_context]
disabled = true

[line_break]
disabled = true

[gcloud]
disabled = true

[package]
disabled = true

